package UTN.FRGP.TP_L5_GRUPO_1.Enums;

public enum ErrorCode {
	DUPLICATED_ACCOUNT,
    DUPLICATED_CUSTOMER,
    INVALID_ID,
    INVALID_DNI,
    INVALID_NAME,
    INVALID_LAST_NAME,
    INVALID_EMAIL,
    INVALID_USERNAME,
    INVALID_MAX_LOAN_AMOUNT,
    INVALID_LOCALITY,
    INVALID_ADDRESS,
    INVALID_BORN_DATE,
    INVALID_GENDER,
}
