package UTN.FRGP.TP_L5_GRUPO_1.Enums;

public enum ErrorCodeEnum {
    ACCOUNTS_MAX_LIMIT,
	DUPLICATED_ACCOUNT,
    DUPLICATED_CUSTOMER,
    INVALID_ALIAS,
    INVALID_CBU,
    INVALID_CREDENTIALS,
    INVALID_ID,
    INVALID_DNI,
    INVALID_NAME,
    INVALID_LAST_NAME,
    INVALID_EMAIL,
    INVALID_USERNAME,
    INVALID_MAX_LOAN_AMOUNT,
    INVALID_LOCALITY,
    INVALID_ADDRESS,
    INVALID_BORN_DATE,
    INVALID_GENDER,
    INVALID_ACCOUNT_TYPE,
    INVALID_AMOUNT,
    INVALID_TRANSFER_ALIAS,
    INVALID_TRANSFER_CUSTOMER,
    INVALID_TRANSFER_ACCOUNT_TYPE,
    INVALID_TRANSFER_BALANCE,
    INVALID_TRANSFER_CBU,
    MISSING_DATA
}
